-- MySQL Script generated by MySQL Workbench
-- Tue Nov  8 14:13:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema document
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `document` ;

-- -----------------------------------------------------
-- Schema document
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `document` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `document` ;

-- -----------------------------------------------------
-- Table `document`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `document`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `document`.`utilisateur` (
  `nom_user` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `mot_passe` VARCHAR(255) NULL,
  PRIMARY KEY (`nom_user`),
  UNIQUE INDEX `nom_utilisateur_UNIQUE` (`nom_user` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `document`.`document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `document`.`document` ;

CREATE TABLE IF NOT EXISTS `document`.`document` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_doc` VARCHAR(255) NULL,
  `nom_user` VARCHAR(255) NULL,
  `url_doc` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `document`.`favoris`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `document`.`favoris` ;

CREATE TABLE IF NOT EXISTS `document`.`favoris` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_doc` VARCHAR(255) NULL,
  `nom_user` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `document`.`amis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `document`.`amis` ;

CREATE TABLE IF NOT EXISTS `document`.`amis` (
  `nom_amis` VARCHAR(255) NOT NULL,
  `utilisateur_nom_user` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`nom_amis`),
  INDEX `fk_amis_utilisateur1_idx` (`utilisateur_nom_user` ASC),
  CONSTRAINT `fk_amis_utilisateur1`
    FOREIGN KEY (`utilisateur_nom_user`)
    REFERENCES `document`.`utilisateur` (`nom_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `document`.`document_utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `document`.`document_utilisateur` ;

CREATE TABLE IF NOT EXISTS `document`.`document_utilisateur` (
  `document_id` INT UNSIGNED NOT NULL,
  `utilisateur_nom_user` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`document_id`, `utilisateur_nom_user`),
  INDEX `fk_document_has_utilisateur_utilisateur1_idx` (`utilisateur_nom_user` ASC),
  INDEX `fk_document_has_utilisateur_document1_idx` (`document_id` ASC),
  CONSTRAINT `fk_document_has_utilisateur_document1`
    FOREIGN KEY (`document_id`)
    REFERENCES `document`.`document` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_has_utilisateur_utilisateur1`
    FOREIGN KEY (`utilisateur_nom_user`)
    REFERENCES `document`.`utilisateur` (`nom_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `document`.`document_favoris`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `document`.`document_favoris` ;

CREATE TABLE IF NOT EXISTS `document`.`document_favoris` (
  `document_id` INT UNSIGNED NOT NULL,
  `favoris_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`document_id`, `favoris_id`),
  INDEX `fk_document_has_favoris_favoris1_idx` (`favoris_id` ASC),
  INDEX `fk_document_has_favoris_document1_idx` (`document_id` ASC),
  CONSTRAINT `fk_document_has_favoris_document1`
    FOREIGN KEY (`document_id`)
    REFERENCES `document`.`document` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_has_favoris_favoris1`
    FOREIGN KEY (`favoris_id`)
    REFERENCES `document`.`favoris` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
